apiVersion: apps/v1
kind: Deployment
metadata:
  name: ribbonstatic
  labels:
    app: ribbonstatic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ribbonstatic
  template:
    metadata:
      labels:
        app: ribbonstatic
    spec:
      containers:
      - name: ribbonstatic-app
        image: jeremyqzt/ribbonstatic
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: fe-http
        - containerPort: 443
          name: fe-https
---
apiVersion: v1
kind: Service
metadata:
  name: ribbonstatic
  labels:
    app: ribbonstatic
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: 'http-ingress'
  - port: 443
    targetPort: 443
    name: 'https-ingress'
  selector:
    app: ribbonstatic