apiVersion: apps/v1
kind: Deployment
metadata:
  name: ribbonstatic
  labels:
    app: ribbonstatic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ribbonstatic
  template:
    metadata:
      labels:
        app: ribbonstatic
    spec:
      containers:
      - name: ribbonstatic-app
        image: jeremyqzt/ribbonstatic
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: static-http
---
apiVersion: v1
kind: Service
metadata:
  name: ribbonstatic
  labels:
    app: ribbonstatic
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: 'http-ingress'
  selector:
    app: ribbonstatic